name: DevSecOps Production Pipeline

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_API: nathalanlemoine/devsecopsapi
  IMAGE_FRONT: nathalanlemoine/devsecopsfront
  # Le dossier sur ta VM où tu veux stocker le projet
  DEPLOY_PATH: /srv/myapp 

jobs:
  # ------------------------------------------
  # ÉTAPE 1 : SAST (Analyse du Code - Cloud)
  # ------------------------------------------
  security-sast:
    name: SAST - Semgrep Analysis
    runs-on: ubuntu-latest
    continue-on-error: true 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Semgrep Security Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          auditOn: push

  # ------------------------------------------
  # ÉTAPE 2 : BUILD & PUSH (Docker - Cloud)
  # ------------------------------------------
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: security-sast
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build & Push API
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: ${{ env.IMAGE_API }}:latest
      
      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.IMAGE_FRONT }}:latest

  # ------------------------------------------
  # ÉTAPE 3 : CONTAINER SCAN (Trivy - Cloud)
  # ------------------------------------------
  security-container:
    name: Scan Vulnerabilities (Trivy)
    runs-on: ubuntu-latest
    needs: build-and-push
    continue-on-error: true
    steps:
      - name: Scan API Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_API }}:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'
      
      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_FRONT }}:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'

  # ------------------------------------------
  # ÉTAPE 4 : DEPLOY (Ta VM - Self Hosted)
  # ------------------------------------------

  deploy:
    name: Deploy on VirtualBox
    needs: security-container
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          # Création du dossier cible
          mkdir -p ${{ env.DEPLOY_PATH }}
          
          # 1. On supprime le dossier monitoring existant sur la VM 
          # (C'est crucial car Docker a créé un "faux" dossier corrompu lors de l'erreur précédente)
          rm -rf ${{ env.DEPLOY_PATH }}/monitoring

          # 2. On copie le fichier docker-compose
          cp docker-compose.yml ${{ env.DEPLOY_PATH }}/

          # 3. On copie le dossier monitoring (avec le prometheus.yml dedans)
          cp -r monitoring ${{ env.DEPLOY_PATH }}/
          
          # ====================================================
          
          # Login Docker
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          # Exécution
          cd ${{ env.DEPLOY_PATH }}
          
          echo "⬇Téléchargement des nouvelles images..."
          docker-compose pull
          
          echo "Redémarrage des services..."
          # On relance tout (le down permet de nettoyer l'état d'erreur précédent)
          docker-compose down
          docker-compose up -d --remove-orphans
          
          echo "Nettoyage..."
          docker image prune -f